lzc-sdk-version: 0.1
name: MoivePilot
package: cloud.lazycat.app.moviepilot
version: 2.3.3-1
description: NAS媒体库自动化管理工具
license: GPL_V3
homepage: https://github.com/jxxghp/MoviePilot
author: jxxghp
application:
  background_task: true
  subdomain: moviepilot
  routes:
    - /=http://mp.cloud.lazycat.app.moviepilot.lzcapp:3000
    - /api=http://mp.cloud.lazycat.app.moviepilot.lzcapp:3001
services:
  mp:
    image: registry.lazycat.cloud/boiaoch/jxxghp/moviepilot-v2:7efe4bb4e4018677
    binds:
      - /lzcapp/var/media:/media
      - /lzcapp/var/moviepilot:/config
      - /lzcapp/cache/core:/moviepilot/.cache/ms-playwright
    environment:
      - NGINX_PORT = 3000
      - PORT = 3001
      - PUID = 0
      - PGID = 0
      - UNMASK = 000
      - TZ = Asia/Shanghai
      - SUPERUSER = admin
